"use client";

import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
const inter = Inter({ subsets: ["latin"] });
import style from "@/css/adminPage.module.css";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <div className="d-flex vh-100 bg-light">
      <SideBar />
      <Container>
        <NavBar />
        {children}
      </Container>
    </div>
  );
}
