export const role = {
    TRANSACTION_POINT_EMPLOYEE: "TRANSACTION_POINT_EMPLOYEE",
    TRANSACTION_POINT_HEAD: "TRANSACTION_POINT_HEAD",
    GOODS_POINT_EMPLOYEE: "GOODS_POINT_EMPLOYEE",
    GOODS_POINT_HEAD: "GOODS_POINT_HEAD",
    MANAGER: "MANAGER"
};