export const role = {
    TRANSACTION_POINT_EMPLOYEE: "TRANSACTION_POINT_EMPLOYEE",
    TRANSACTION_POINT_HEADER: "TRANSACTION_POINT_HEADER",
    GOODS_POINT_EMPLOYEE: "GOODS_POINT_EMPLOYEE",
    GOODS_POINT_HEADER: "GOODS_POINT_HEADER",
    MANAGER: "MANAGER"
};