"use client";

import AppHeader from "@/components/header";
import { Inter } from "next/font/google";
import { Container, Navbar } from "react-bootstrap";
// import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader></AppHeader>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
